import React, { useState } from "react";
import { RealApp } from "./RealApp";
import { LiveCatalog } from "./LiveCatalog";
import {
  House, MagnifyingGlass, Ticket, UserCircle, MapPin, CalendarBlank, Bell, Heart,
  ArrowLeft, ArrowRight, SquaresFour, Plus, Armchair, QrCode, Wallet, ChartBar,
  UsersThree, Gear, ClipboardText, WarningCircle, CheckCircle, Clock, Funnel,
  Eye, PencilSimple, FileText, CaretDown, X, ShieldCheck, CurrencyCircleDollar,
  TrendUp, Rows, Camera, DownloadSimple, Copy, Check, PaperPlaneTilt
} from "@phosphor-icons/react";

const fa = new Intl.NumberFormat("fa-IR");
const roles={buyer:["خریدار","وب‌سایت صحنو"],organizer:["برگزارکننده","پنل برگزارکننده"],ops:["عملیات","پنل عملیات"]};

function Logo({mini=false}){return <div className="brand"><img src="/assets/sahno-logo.png" alt="نشان صحنو"/>{!mini&&<div><b>صحنو</b><small>رویداد زنده، روشن و ساده</small></div>}</div>}
function Badge({tone="purple",children}){return <span className={`badge ${tone}`}>{children}</span>}
function Card({className="",children}){return <section className={`card ${className}`}>{children}</section>}
function RoleSwitch({role,setRole}){const[open,setOpen]=useState(false);return <div className="role-switch"><button onClick={()=>setOpen(!open)}><UserCircle/><span><b>{roles[role][0]}</b><small>{roles[role][1]}</small></span><CaretDown/></button>{open&&<div className="role-menu">{Object.entries(roles).map(([k,v])=><button key={k} className={k===role?"active":""} onClick={()=>{setRole(k);setOpen(false)}}><b>{v[0]}</b><small>{v[1]}</small></button>)}</div>}</div>}
function Primary({children,onClick,disabled=false,className=""}){return <button disabled={disabled} className={`primary ${className}`} onClick={onClick}>{children}</button>}
function Stat({label,value,icon:Icon,tone="purple",note}){return <Card className={`stat ${tone}`}><i><Icon/></i><div><small>{label}</small><strong>{value}</strong>{note&&<em>{note}</em>}</div></Card>}

function BuyerHeader({role,setRole}){return <header className="buyer-head"><Logo/><div><button className="icon"><Bell/></button><RoleSwitch role={role} setRole={setRole}/></div></header>}
function Buyer({role,setRole}){
 const[page,setPage]=useState("home"),[query,setQuery]=useState(""),[session,setSession]=useState("۱۸:۰۰"),[selected,setSelected]=useState(["D12","D13"]),[paid,setPaid]=useState(false);
 const seats=Array.from({length:56},(_,i)=>({id:`${String.fromCharCode(65+Math.floor(i/8))}${i%8+1}`,sold:[3,7,12,18,19,25,31,38,45].includes(i)}));
 const back=<button className="text" onClick={()=>setPage(page==="event"?"home":page==="seats"?"event":page==="checkout"?"seats":"home")}><ArrowRight/> بازگشت</button>;
 let body;
 if(page==="home") body=<><section className="welcome"><Badge>تهران</Badge><h1>سلام، امشب کجا می‌ریم؟</h1><div className="search"><MagnifyingGlass/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="جست‌وجوی اجرا، هنرمند یا سالن"/><Funnel/></div><div className="chips">{["همه","کنسرت","تئاتر","جشنواره","کودک"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</div></section><Title title="پیشنهاد ویژه"/><Card className="featured"><div className="photo"><img src="/assets/concert-hero.png" alt="اجرای زنده"/><Badge tone="coral">فروش ویژه</Badge><button><Heart/></button></div><div className="event-copy"><h2>کنسرت محسن چاووشی</h2><p><CalendarBlank/> پنجشنبه ۱۸ مهر · ساعت ۱۸:۰۰</p><p><MapPin/> سالن نمونه تهران</p><div><strong>از ۱٬۲۰۰٬۰۰۰ تومان</strong><Primary onClick={()=>setPage("event")}>خرید بلیت <Ticket/></Primary></div></div></Card><Title title="این هفته"/><div className="event-grid">{["کنسرت محسن چاووشی","نمایش بی‌پایان","اجرای گروه نمونه"].filter(x=>x.includes(query)||!query).map((x,i)=><Card className="event-small" key={x}><img src="/assets/concert-hero.png"/><Badge tone={i?"neutral":"purple"}>{i?"فروش فعال":"ظرفیت محدود"}</Badge><h3>{x}</h3><p>پنجشنبه {fa.format(18+i)} مهر · ساعت ۲۰:۰۰</p><small>تهران، سالن نمونه</small><button className="ghost" onClick={()=>setPage("event")}>جزئیات و خرید</button></Card>)}</div></>;
 if(page==="event") body=<>{back}<Card className="event-detail"><img src="/assets/concert-hero.png"/><div><Badge tone="success">در حال فروش</Badge><h1>کنسرت محسن چاووشی</h1><p>یک شب موسیقی زنده در سالن نمونه تهران</p></div></Card><h2>انتخاب سانس</h2><div className="sessions">{["۱۸:۰۰","۲۱:۳۰"].map(t=><button onClick={()=>setSession(t)} className={session===t?"active":""} key={t}><b>پنجشنبه ۱۸ مهر</b><span>ساعت {t}</span></button>)}</div><Card className="info"><Info icon={MapPin} title="سالن نمونه تهران" text="تهران، خیابان انقلاب" map/><Info icon={CurrencyCircleDollar} title="محدوده قیمت" text="۱٬۲۰۰٬۰۰۰ تا ۲٬۴۰۰٬۰۰۰ تومان"/><Info icon={FileText} title="قوانین خرید و استرداد" text="مشاهده شرایط این اجرا"/></Card><Sticky text={`پنجشنبه ۱۸ مهر، ساعت ${session}`} value="از ۱٬۲۰۰٬۰۰۰ تومان"><Primary onClick={()=>setPage("seats")}>انتخاب صندلی <ArrowLeft/></Primary></Sticky></>;
 if(page==="seats") body=<>{back}<h1>انتخاب صندلی</h1><Card className="mini-event"><img src="/assets/concert-hero.png"/><div><b>کنسرت محسن چاووشی</b><span>پنجشنبه ۱۸ مهر · ساعت {session}</span><small>سالن نمونه تهران</small></div></Card><Card className="seat-card"><div className="stage">صحنه</div><div className="seats">{seats.map(s=><button key={s.id} disabled={s.sold} className={`${s.sold?"sold":""} ${selected.includes(s.id)?"chosen":""}`} onClick={()=>!s.sold&&setSelected(a=>a.includes(s.id)?a.filter(x=>x!==s.id):[...a,s.id])}>{s.id.slice(1)}</button>)}</div><Legend/></Card><Card className="choice"><span>صندلی‌های انتخاب‌شده</span><b>{selected.length?selected.join("، "):"صندلی انتخاب نشده"}</b></Card><Sticky text={`${fa.format(selected.length)} صندلی`} value={`${fa.format(selected.length*1800000)} تومان`}><Primary disabled={!selected.length} onClick={()=>setPage("checkout")}>ادامه و ورود <ArrowLeft/></Primary></Sticky></>;
 if(page==="checkout") body=<>{back}<h1>تکمیل خرید</h1>{!paid?<><Card><h3>اطلاعات خریدار</h3><div className="form"><label>نام و نام خانوادگی<input defaultValue="سبحان رضایی"/></label><label>شماره موبایل<input defaultValue="۰۹۱۲ ۳۴۵ ۶۷۸۹"/></label><label className="wide">ایمیل<input defaultValue="sobhan@example.com"/></label></div></Card><Card><h3>خلاصه سفارش</h3><Row a="کنسرت محسن چاووشی" b={session}/><Row a="صندلی‌ها" b={selected.join("، ")}/><Row a="مبلغ نهایی" b={`${fa.format(selected.length*1800000)} تومان`}/></Card><Primary className="full" onClick={()=>setPaid(true)}>پرداخت آزمایشی و دریافت بلیت</Primary></>:<Card className="success"><CheckCircle/><h2>خرید با موفقیت انجام شد</h2><p>بلیت شما صادر شد و از بخش «بلیت‌های من» در دسترس است.</p><b>شماره سفارش: S-1024</b><Primary onClick={()=>setPage("tickets")}>مشاهده بلیت‌ها</Primary></Card>}</>;
 if(page==="tickets") body=<><h1>بلیت‌های من</h1><Card className="ticket-card"><div><Badge tone="success">معتبر</Badge><Logo mini/></div><h2>کنسرت محسن چاووشی</h2><p>پنجشنبه ۱۸ مهر ۱۴۰۵ · ساعت {session}</p><div className="qr"><QrCode/></div><b>ردیف D · صندلی ۱۲ و ۱۳</b><div className="buttons"><button className="ghost"><DownloadSimple/> ذخیره</button><button className="ghost"><Copy/> کپی کد</button></div></Card></>;
 return <div className="buyer"><BuyerHeader role={role} setRole={setRole}/><main className={page==="home"?"buyer-main":"buyer-main narrow"}>{body}</main><nav className="mobile-nav">{[[House,"خانه","home"],[MagnifyingGlass,"جست‌وجو","home"],[Ticket,"بلیت‌ها","tickets"],[UserCircle,"حساب من","home"]].map(([I,t,p])=><button className={page===p?"active":""} onClick={()=>setPage(p)} key={t}><I/><span>{t}</span></button>)}</nav></div>
}
function Title({title}){return <div className="title"><h2>{title}</h2><button>مشاهده همه <ArrowLeft/></button></div>}
function Info({icon:Icon,title,text,map}){return <div className="info-row"><Icon/><div><b>{title}</b><span>{text}</span></div>{map&&<button onClick={()=>window.open("https://www.google.com/maps/search/?api=1&query=سالن+نمونه+تهران","_blank")}>مسیریابی <ArrowLeft/></button>}</div>}
function Sticky({text,value,children}){return <div className="sticky"><div><small>{text}</small><b>{value}</b></div>{children}</div>}
function Legend(){return <div className="legend"><span><i/>موجود</span><span><i className="chosen"/>انتخاب‌شده</span><span><i className="sold"/>فروخته‌شده</span></div>}
function Row({a,b}){return <div className="row"><span>{a}</span><b>{b}</b></div>}

const orgNav=[["dashboard","داشبورد",SquaresFour],["events","اجراها",CalendarBlank],["orders","فروش و سفارش‌ها",Ticket],["capacity","صندلی‌ها و سالن",Armchair],["scan","کنترل ورود",QrCode],["settlement","تسویه‌حساب",Wallet],["reports","گزارش‌ها",ChartBar],["team","تیم و دسترسی‌ها",UsersThree]];
const opsNav=[["queue","رویدادها",ClipboardText],["organizers","برگزارکنندگان",UsersThree],["orders","سفارش‌ها",Ticket],["settlement","تسویه‌ها",Wallet],["violations","گزارش تخلف",WarningCircle],["access","کاربران و دسترسی",ShieldCheck]];
function Shell({role,setRole,active,setActive,nav,children}){return <div className="shell"><aside><Logo/><small className="panel-name">{roles[role][1]}</small><nav>{nav.map(([k,t,I])=><button className={active===k?"active":""} onClick={()=>setActive(k)} key={k}><I/><span>{t}</span></button>)}</nav><button className="settings"><Gear/><span>تنظیمات</span></button></aside><section className="workspace"><header><div className="dash-search"><MagnifyingGlass/><input placeholder="جست‌وجو..."/></div><div><button className="icon"><Bell/></button><RoleSwitch role={role} setRole={setRole}/></div></header>{children}</section></div>}
function PageHead({title,sub,action,onAction}){return <div className="page-head"><div><Badge>نمونه نمایشی</Badge><h1>{title}</h1><p>{sub}</p></div>{action&&<Primary onClick={onAction}><Plus/>{action}</Primary>}</div>}
function Organizer({role,setRole}){const[active,setActive]=useState("dashboard"),[create,setCreate]=useState(false);let content;if(active==="dashboard")content=<Dashboard create={()=>setCreate(true)} go={setActive}/>;if(active==="events")content=<Events create={()=>setCreate(true)}/>;if(active==="orders")content=<Orders/>;if(active==="capacity")content=<Capacity/>;if(active==="scan")content=<Scan/>;if(active==="settlement")content=<Settlement/>;if(active==="reports")content=<Reports/>;if(active==="team")content=<Team/>;return <Shell role={role} setRole={setRole} nav={orgNav} active={active} setActive={setActive}><main className="dash-main">{content}</main>{create&&<Create close={()=>setCreate(false)}/>}</Shell>}
function Dashboard({create,go}){return <><PageHead title="داشبورد فروش" sub="کنسرت محسن چاووشی · به‌روزرسانی همین حالا" action="ایجاد اجرای جدید" onAction={create}/><div className="stats"><Stat label="فروش ناخالص" value="۸۲۴ میلیون" note="تومان" icon={CurrencyCircleDollar}/><Stat label="بلیت فروخته‌شده" value="۳۴۲" note="از ۸۴۰" icon={Ticket} tone="blue"/><Stat label="تکمیل ظرفیت" value="۴۱٪" note="۲ سانس" icon={TrendUp} tone="teal"/><Stat label="سفارش امروز" value="۲۸" note="۱۲٪ رشد" icon={Rows} tone="coral"/></div><div className="columns"><Card><h3>روند فروش هفت‌روزه</h3><Bars values={[34,48,42,65,58,82,71]}/></Card><Card><h3>وضعیت اجرا</h3><div className="ring"><b>۴۱٪</b><small>تکمیل ظرفیت</small></div><Row a="ظرفیت کل" b="۸۴۰"/><Row a="فروخته‌شده" b="۳۴۲"/><button className="ghost full" onClick={()=>go("capacity")}>مشاهده صندلی‌ها</button></Card></div><OrdersTable/></>}
function Bars({values,tall=false}){return <div className={`bars ${tall?"tall":""}`}>{values.map((x,i)=><div key={i}><span style={{height:`${x}%`}}/><small>{fa.format(i+1)}</small></div>)}</div>}
function Events({create}){return <><PageHead title="اجراها" sub="مدیریت اجراهای پیش‌نویس، در حال بررسی و منتشرشده" action="ایجاد اجرای جدید" onAction={create}/><Filters/><Card><DataTable type="events"/></Card></>}
function Filters(){return <div className="filters"><div className="search"><MagnifyingGlass/><input placeholder="جست‌وجو"/></div>{["همه","منتشرشده","در حال بررسی"].map((x,i)=><button className={i===0?"active":""} key={x}>{x}</button>)}</div>}
function Orders(){return <><PageHead title="فروش و سفارش‌ها" sub="پیگیری سفارش‌ها و بلیت‌های صادرشده"/><div className="stats three"><Stat label="کل سفارش‌ها" value="۲۹۸" icon={Ticket}/><Stat label="پرداخت موفق" value="۲۸۶" icon={CheckCircle} tone="teal"/><Stat label="در انتظار پرداخت" value="۱۲" icon={Clock} tone="coral"/></div><OrdersTable/></>}
function OrdersTable(){return <Card><div className="card-head"><h3>آخرین سفارش‌ها</h3><div className="search"><MagnifyingGlass/><input placeholder="شماره سفارش یا موبایل"/></div></div><DataTable type="orders"/></Card>}
function DataTable({type}){if(type==="events")return <table><thead><tr><th>اجرا</th><th>تاریخ</th><th>وضعیت</th><th>فروش</th><th></th></tr></thead><tbody><tr><td><b>کنسرت محسن چاووشی</b><small>سالن نمونه تهران</small></td><td>۱۸ مهر ۱۴۰۵</td><td><Badge tone="success">منتشرشده</Badge></td><td>۳۴۲ بلیت</td><td><button className="icon"><Eye/></button></td></tr><tr><td><b>اجرای پاییزی</b><small>پیش‌نویس</small></td><td>۲۸ مهر ۱۴۰۵</td><td><Badge tone="neutral">پیش‌نویس</Badge></td><td>—</td><td><button className="icon"><PencilSimple/></button></td></tr></tbody></table>;if(type==="pricing")return <table><thead><tr><th>بخش</th><th>ظرفیت</th><th>قیمت هر بلیت</th></tr></thead><tbody><tr><td><b>VIP</b></td><td>۲۴۰</td><td>۲٬۴۰۰٬۰۰۰ تومان</td></tr><tr><td><b>همکف</b></td><td>۲۸۰</td><td>۱٬۸۰۰٬۰۰۰ تومان</td></tr><tr><td><b>بالکن</b></td><td>۳۲۰</td><td>۱٬۲۰۰٬۰۰۰ تومان</td></tr></tbody></table>;return <table><thead><tr><th>سفارش</th><th>خریدار</th><th>سانس</th><th>مبلغ</th><th>وضعیت</th></tr></thead><tbody>{[["S-1024","سبحان رضایی","۱۸:۰۰","۳٬۶۰۰٬۰۰۰"],["S-1023","نگار محمدی","۲۱:۳۰","۲٬۴۰۰٬۰۰۰"],["S-1022","حامد کریمی","۱۸:۰۰","۱٬۸۰۰٬۰۰۰"]].map(r=><tr key={r[0]}>{r.map(x=><td key={x}>{x}</td>)}<td><Badge tone="success">پرداخت‌شده</Badge></td></tr>)}</tbody></table>}
function Capacity(){return <><PageHead title="نقشه صندلی‌ها و ظرفیت" sub="سانس ۱۸ مهر · ساعت ۱۸:۰۰"/><div className="columns capacity"><Card><div className="stage">صحنه</div><div className="admin-seats">{Array.from({length:80},(_,i)=><i key={i} className={i%7===0?"sold":i%11===0?"held":i%17===0?"locked":""}/>)}</div><Legend/></Card><div><Stat label="ظرفیت کل" value="۸۴۰" icon={Armchair}/><Stat label="فروخته‌شده" value="۳۴۲" icon={Ticket} tone="teal"/><Stat label="موجود" value="۴۷۶" icon={CheckCircle} tone="blue"/></div></div></>}
function Scan(){const[scan,setScan]=useState(false);return <><PageHead title="کنترل ورود" sub="اسکن بلیت و ثبت ورود مهمانان"/><div className="stats three"><Stat label="واردشده" value={scan?"۱۸۷":"۱۸۶"} icon={CheckCircle} tone="teal"/><Stat label="در انتظار" value={scan?"۱۵۵":"۱۵۶"} icon={UsersThree}/><Stat label="نامعتبر" value="۳" icon={WarningCircle} tone="coral"/></div><div className="columns"><Card className="scanner"><Camera/><h2>کد QR بلیت را اسکن کنید</h2><p>دوربین را روبه‌روی کد بلیت نگه دارید.</p><Primary onClick={()=>setScan(true)}>شبیه‌سازی اسکن</Primary></Card><Card className={`scan-result ${scan?"valid":""}`}>{scan?<><CheckCircle/><Badge tone="success">بلیت معتبر</Badge><h2>سبحان رضایی</h2><Row a="صندلی" b="ردیف D، صندلی ۱۲"/><Row a="سانس" b="۱۸ مهر · ۱۸:۰۰"/><button className="ghost full" onClick={()=>setScan(false)}>اسکن بعدی</button></>:<><QrCode/><h3>نتیجه اسکن اینجا نمایش داده می‌شود</h3></>}</Card></div></>}
function Settlement(){return <><PageHead title="تسویه‌حساب" sub="مشاهده درآمد و چرخه تسویه اجرا"/><div className="stats three"><Stat label="فروش ناخالص" value="۸۲۴ میلیون" icon={CurrencyCircleDollar}/><Stat label="کارمزد صحنو" value="۴۱٫۲ میلیون" icon={Wallet} tone="blue"/><Stat label="قابل پرداخت" value="۷۸۲٫۸ میلیون" icon={CheckCircle} tone="teal"/></div><div className="columns"><Card><h3>چرخه تسویه</h3>{[["فروش رویداد","تکمیل‌شده"],["پایان اجرا","۱۸ مهر"],["بررسی مالی","۲ روز کاری"],["واریز","۲۲ مهر"]].map((x,i)=><div className="timeline" key={x[0]}><i className={i<2?"done":""}>{i<2?<Check/>:i+1}</i><div><b>{x[0]}</b><small>{x[1]}</small></div></div>)}</Card><Card><h3>حساب بانکی مقصد</h3><div className="bank"><small>شماره شبا</small><b>IR ۳۷۰۵۶۰۰۸۰۰۰۰۱۲۳۴۵۶۷۸۹۰۱</b><span>به نام آرتین رضایی</span></div><button className="ghost full">ویرایش اطلاعات مالی</button></Card></div></>}
function Reports(){return <><PageHead title="گزارش‌ها" sub="تحلیل فروش، سانس‌ها و ورود مهمانان"/><button className="ghost export"><DownloadSimple/> خروجی گزارش</button><Card><h3>فروش ۳۰ روز اخیر</h3><Bars tall values={[24,31,28,45,39,55,64,58,72,69,84,77]}/></Card></>}
function Team(){const[sent,setSent]=useState(false);return <><PageHead title="تنظیمات و تیم" sub="اطلاعات برگزارکننده و سطح دسترسی اعضا"/><div className="columns equal"><Card><h3>اطلاعات برگزارکننده</h3><div className="form"><label>نام<input defaultValue="آرتین رویداد"/></label><label>موبایل<input defaultValue="۰۹۱۲ ۳۴۵ ۶۷۸۹"/></label><label className="wide">ایمیل<input defaultValue="artin@rooydad.ir"/></label></div><button className="ghost">ذخیره تغییرات</button></Card><Card><div className="card-head"><h3>اعضای تیم</h3><Primary onClick={()=>setSent(true)}><Plus/>دعوت عضو</Primary></div>{[["آرتین رضایی","مدیر اصلی"],["نگار محمدی","کارشناس فروش"],["حامد کریمی","اپراتور ورود"]].map(x=><div className="member" key={x[0]}><UserCircle/><div><b>{x[0]}</b><small>{x[1]}</small></div><Badge tone="success">فعال</Badge></div>)}{sent&&<p className="done"><CheckCircle/> دعوت‌نامه ارسال شد.</p>}</Card></div></>}
function Create({close}){const[step,setStep]=useState(1),names=["اطلاعات پایه","سانس‌ها","سالن","قیمت‌گذاری","بازبینی"];return <div className="overlay"><div className="modal"><div className="modal-head"><div><Badge>ایجاد اجرای جدید</Badge><h2>{names[step-1]}</h2></div><button className="icon" onClick={close}><X/></button></div><div className="steps">{names.map((x,i)=><div className={step===i+1?"active":step>i+1?"done":""} key={x}><i>{step>i+1?<Check/>:i+1}</i><small>{x}</small></div>)}</div><div className="modal-body">{step===1&&<div className="form"><label className="wide">عنوان اجرا<input defaultValue="کنسرت محسن چاووشی"/></label><label>دسته‌بندی<input defaultValue="موسیقی"/></label><label>شهر<input defaultValue="تهران"/></label></div>}{step===2&&<div className="form"><label>تاریخ<input defaultValue="۱۸ مهر ۱۴۰۵"/></label><label>ساعت<input defaultValue="۱۸:۰۰"/></label></div>}{step===3&&<div className="form"><label className="wide">نام سالن<input defaultValue="سالن نمونه تهران"/></label><label>ظرفیت<input defaultValue="۸۴۰"/></label><label>تعداد بخش‌ها<input defaultValue="۳"/></label></div>}{step===4&&<DataTable type="pricing"/>}{step===5&&<div className="success"><CheckCircle/><h2>اطلاعات اجرا آماده ارسال است</h2><p>۲ سانس، ۸۴۰ صندلی و ۳ محدوده قیمتی ثبت شده است.</p></div>}</div><div className="modal-actions"><button className="ghost" onClick={()=>step>1?setStep(step-1):close()}>{step>1?"مرحله قبل":"انصراف"}</button><Primary onClick={()=>step<5?setStep(step+1):close()}>{step<5?"ادامه":"ارسال برای بررسی"}<ArrowLeft/></Primary></div></div></div>}

function Ops({role,setRole}){const[active,setActive]=useState("queue");const pages={queue:<Queue/>,organizers:<OpsOrganizers/>,orders:<OpsOrders/>,settlement:<OpsSettlements/>,violations:<OpsViolations/>,access:<OpsAccess/>};return <Shell role={role} setRole={setRole} nav={opsNav} active={active} setActive={setActive}><main className="dash-main">{pages[active]}</main></Shell>}
function Queue(){const[status,setStatus]=useState("در انتظار بررسی"),[detail,setDetail]=useState(false),[filter,setFilter]=useState("همه");const rows=[{t:"کنسرت محسن چاووشی",o:"آرتین رضایی",d:"۱۸ مهر · ۲ سانس",s:status,f:"مدرک ظرفیت، اطلاعات سالن"},{t:"اجرای زنده گروه نمونه",o:"نگار محمدی",d:"۲۲ مهر · ۱ سانس",s:"نیازمند اصلاح",f:"تصویر پوستر، قوانین استرداد"},{t:"تئاتر شب آخر",o:"خانه هنر",d:"۲۸ مهر · ۳ سانس",s:"آماده انتشار",f:"بدون مورد باز"}];return <><PageHead title="صف بررسی رویدادها" sub="مدیریت و بازبینی رویدادهای ارسالی"/><div className="stats"><Stat label="در انتظار بررسی" value="۱۲" icon={Clock} tone="coral"/><Stat label="نیازمند اصلاح" value="۳" icon={PencilSimple} tone="blue"/><Stat label="آماده انتشار" value="۵" icon={PaperPlaneTilt} tone="teal"/><Stat label="منتشرشده" value="۲۸" icon={CheckCircle}/></div><div className="filters"><div className="search"><MagnifyingGlass/><input placeholder="نام رویداد یا برگزارکننده"/></div>{["همه","در انتظار بررسی","نیازمند اصلاح","آماده انتشار"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><Card><table><thead><tr><th>رویداد</th><th>برگزارکننده</th><th>تاریخ</th><th>وضعیت</th><th>موارد بررسی</th><th></th></tr></thead><tbody>{rows.filter(x=>filter==="همه"||x.s===filter).map(r=><tr key={r.t}><td><b>{r.t}</b></td><td>{r.o}</td><td>{r.d}</td><td><Badge tone={r.s==="آماده انتشار"?"success":r.s==="نیازمند اصلاح"?"blue":"warning"}>{r.s}</Badge></td><td>{r.f}</td><td><Primary onClick={()=>setDetail(true)}>بررسی</Primary></td></tr>)}</tbody></table></Card><div className="columns"><Card><h3>راهنمای وضعیت</h3><Row a="در انتظار بررسی" b="توسط تیم عملیات"/><Row a="نیازمند اصلاح" b="اقدام برگزارکننده"/><Row a="آماده انتشار" b="تأیید نهایی"/></Card><Card><h3>آخرین فعالیت‌ها</h3><div className="activity"><FileText/><div><b>مدرک ظرفیت درخواست شد</b><small>۱۲ دقیقه پیش</small></div></div><div className="activity"><PencilSimple/><div><b>وضعیت رویداد تغییر کرد</b><small>۲۵ دقیقه پیش</small></div></div></Card></div>{detail&&<div className="drawer-bg" onClick={()=>setDetail(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>بررسی رویداد</h2><button className="icon" onClick={()=>setDetail(false)}><X/></button></div><img src="/assets/concert-hero.png"/><h2>کنسرت محسن چاووشی</h2><Badge tone={status==="آماده انتشار"?"success":"warning"}>{status}</Badge><Card className="checks"><h3>چک‌لیست بررسی</h3>{["اطلاعات اجرا","سانس‌ها و زمان‌بندی","قیمت‌ها","مدرک ظرفیت سالن"].map((x,i)=><label key={x}><input type="checkbox" defaultChecked={i<3}/>{x}</label>)}</Card><label className="note">یادداشت<textarea defaultValue="لطفاً مدرک تأییدیه ظرفیت سالن را بارگذاری کنید."/></label><div className="drawer-actions"><button className="ghost" onClick={()=>setStatus("نیازمند اصلاح")}>درخواست اصلاح</button><Primary onClick={()=>{setStatus("آماده انتشار");setDetail(false)}}>تأیید نهایی</Primary></div></aside></div>}</>}
function OpsOrganizers(){const[verified,setVerified]=useState(["آرتین رویداد","خانه هنر"]);const list=[["آرتین رویداد","آرتین رضایی","۳ اجرا","۸۲۴ میلیون"],["خانه هنر","مریم احمدی","۵ اجرا","۳۶۵ میلیون"],["رویداد آبی","سامان پورمحمدی","۱ اجرا","۸۹ میلیون"]];return <><PageHead title="برگزارکنندگان" sub="بررسی هویت، وضعیت حساب و عملکرد برگزارکنندگان"/><div className="stats three"><Stat label="برگزارکننده فعال" value="۲۸" icon={UsersThree} tone="teal"/><Stat label="در انتظار احراز" value="۳" icon={Clock} tone="coral"/><Stat label="مجموع اجراها" value="۶۴" icon={CalendarBlank}/></div><Filters/><Card><table><thead><tr><th>برگزارکننده</th><th>مدیر حساب</th><th>اجراها</th><th>فروش کل</th><th>احراز هویت</th><th></th></tr></thead><tbody>{list.map(r=><tr key={r[0]}><td><b>{r[0]}</b><small>شناسه ORG-{fa.format(102+list.indexOf(r))}</small></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td><Badge tone={verified.includes(r[0])?"success":"warning"}>{verified.includes(r[0])?"تأییدشده":"در انتظار"}</Badge></td><td><button className="ghost compact" onClick={()=>setVerified(v=>v.includes(r[0])?v:[...v,r[0]])}>{verified.includes(r[0])?<Eye/>:<Check/>}{verified.includes(r[0])?"مشاهده":"تأیید"}</button></td></tr>)}</tbody></table></Card></>}
function OpsOrders(){const[refunded,setRefunded]=useState([]);const orders=[["S-1024","سبحان رضایی","کنسرت محسن چاووشی","۳٬۶۰۰٬۰۰۰"],["S-1023","نگار محمدی","کنسرت محسن چاووشی","۲٬۴۰۰٬۰۰۰"],["S-1022","حامد کریمی","تئاتر شب آخر","۱٬۸۰۰٬۰۰۰"]];return <><PageHead title="سفارش‌ها" sub="پیگیری پرداخت، صدور بلیت و درخواست‌های استرداد"/><div className="stats three"><Stat label="سفارش موفق امروز" value="۱۸۶" icon={CheckCircle} tone="teal"/><Stat label="پرداخت ناموفق" value="۹" icon={WarningCircle} tone="coral"/><Stat label="درخواست استرداد" value="۴" icon={Wallet}/></div><Filters/><Card><table><thead><tr><th>شماره سفارش</th><th>خریدار</th><th>رویداد</th><th>مبلغ</th><th>وضعیت</th><th></th></tr></thead><tbody>{orders.map(r=><tr key={r[0]}><td><b>{r[0]}</b><small>۲۴ شهریور ۱۴۰۵</small></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]} تومان</td><td><Badge tone={refunded.includes(r[0])?"neutral":"success"}>{refunded.includes(r[0])?"مسترد شد":"پرداخت‌شده"}</Badge></td><td><button className="ghost compact" onClick={()=>setRefunded(x=>x.includes(r[0])?x:[...x,r[0]])}>{refunded.includes(r[0])?"مشاهده":"ثبت استرداد"}</button></td></tr>)}</tbody></table></Card></>}
function OpsSettlements(){const[paid,setPaid]=useState(["SET-210"]);const rows=[["SET-212","آرتین رویداد","۷۸۲٬۸۰۰٬۰۰۰","۲۲ مهر"],["SET-211","خانه هنر","۱۴۸٬۵۰۰٬۰۰۰","۲۴ مهر"],["SET-210","رویداد آبی","۷۶٬۲۰۰٬۰۰۰","۲۰ شهریور"]];return <><PageHead title="تسویه‌ها" sub="کنترل مبالغ قابل پرداخت و وضعیت واریز برگزارکنندگان"/><div className="stats three"><Stat label="قابل پرداخت" value="۱٫۰۱ میلیارد" icon={CurrencyCircleDollar}/><Stat label="در انتظار تأیید" value="۲" icon={Clock} tone="coral"/><Stat label="واریزشده این ماه" value="۲٫۸ میلیارد" icon={CheckCircle} tone="teal"/></div><Card><table><thead><tr><th>شناسه</th><th>برگزارکننده</th><th>مبلغ</th><th>موعد</th><th>وضعیت</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]} تومان</td><td>{r[3]}</td><td><Badge tone={paid.includes(r[0])?"success":"warning"}>{paid.includes(r[0])?"واریزشده":"در انتظار تأیید"}</Badge></td><td><Primary onClick={()=>setPaid(x=>x.includes(r[0])?x:[...x,r[0]])}>{paid.includes(r[0])?<Eye/>:<Check/>}{paid.includes(r[0])?"رسید":"تأیید"}</Primary></td></tr>)}</tbody></table></Card></>}
function OpsViolations(){const[resolved,setResolved]=useState([]);const items=[["V-104","مغایرت قیمت نمایش‌داده‌شده","کنسرت نمونه","زیاد"],["V-103","گزارش رفتار نامناسب ورودی","تئاتر شب آخر","متوسط"],["V-102","مشکل بازیابی بلیت","اجرای زنده گروه نمونه","کم"]];return <><PageHead title="گزارش تخلف" sub="رسیدگی به گزارش‌های خریداران و موارد نیازمند پیگیری"/><div className="stats three"><Stat label="پرونده باز" value="۷" icon={WarningCircle} tone="coral"/><Stat label="در حال پیگیری" value="۴" icon={Clock}/><Stat label="حل‌شده این ماه" value="۲۳" icon={CheckCircle} tone="teal"/></div><Card><table><thead><tr><th>شناسه</th><th>موضوع</th><th>رویداد</th><th>اولویت</th><th>وضعیت</th><th></th></tr></thead><tbody>{items.map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td><td><Badge tone={r[3]==="زیاد"?"coral":r[3]==="متوسط"?"warning":"blue"}>{r[3]}</Badge></td><td>{resolved.includes(r[0])?"بسته‌شده":"باز"}</td><td><button className="ghost compact" onClick={()=>setResolved(x=>x.includes(r[0])?x:[...x,r[0]])}>{resolved.includes(r[0])?"مشاهده":"بستن پرونده"}</button></td></tr>)}</tbody></table></Card></>}
function OpsAccess(){const[invite,setInvite]=useState(false);return <><PageHead title="کاربران و دسترسی" sub="مدیریت اعضای تیم عملیات و سطح دسترسی هر نقش" action="دعوت کاربر" onAction={()=>setInvite(true)}/><div className="columns equal"><Card><h3>اعضای تیم عملیات</h3>{[["علی محمدی","کارشناس عملیات","بررسی رویداد"],["سارا احمدی","مدیر مالی","تسویه‌ها"],["رضا حاتمی","پشتیبان","سفارش‌ها و تخلف"]].map(x=><div className="member" key={x[0]}><UserCircle/><div><b>{x[0]}</b><small>{x[1]} · {x[2]}</small></div><Badge tone="success">فعال</Badge></div>)}{invite&&<p className="done"><CheckCircle/> دعوت‌نامه آزمایشی ثبت شد.</p>}</Card><Card><h3>نقش‌ها و مجوزها</h3><Row a="مدیر عملیات" b="دسترسی کامل"/><Row a="کارشناس بررسی" b="رویدادها و برگزارکنندگان"/><Row a="مدیر مالی" b="سفارش‌ها و تسویه‌ها"/><Row a="پشتیبان" b="مشاهده و پیگیری"/><button className="ghost full"><Gear/> ویرایش سطح دسترسی‌ها</button></Card></div></>}

export function App(){const[role,setRole]=useState("ops");if(window.location.pathname.replace(/\/$/,"")==="/mvp")return <LiveCatalog/>;if(import.meta.env.VITE_SUPABASE_URL&&import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY)return <RealApp/>;return <><div className="demo-banner" role="status">نسخهٔ نمایشی صحنو · رویدادها، سفارش‌ها و پرداخت‌های این نسخه واقعی نیستند.</div>{role==="buyer"?<Buyer role={role} setRole={setRole}/>:role==="organizer"?<Organizer role={role} setRole={setRole}/>:<Ops role={role} setRole={setRole}/>}</>}
